### ISSUE TITLE
Hex Color Codes

### ISSUE THREAD

**Issue by TheCiROMG** [Lorenzo0111/RocketJoin#13]
**What type of feature is it?**
![image](https://user-images.githubusercontent.com/61605643/120911790-765e8c80-c660-11eb-85bc-a1bba169279e.png)

- [ ] NONE
- [ ] Config option : hex-color-code-compatibility: true
- [ ] NONE

**Describe your feature**
That I can use Hex colors for aesthetics, logging, others, since it is currently ugly

![image](https://user-images.githubusercontent.com/61605643/120911833-ac037580-c660-11eb-9495-f20645469dd2.png)

**Comment by Lorenzo0111** [comment]
Hey, thanks for opening an issue. The feature is a great idea, I’ll add it today

**Comment by Lorenzo0111** [comment]
Done, I'll publish the update in some hours.

**Comment by Lorenzo0111** [comment]
Released on SpigotMC.

Remember to leave a review on spigot 😁.
