### ISSUE TITLE
[Feature] Store joined players on Bungee

### ISSUE THREAD

**Issue by belzaaron** [Lorenzo0111/RocketJoin#35]
**What type of feature is it?**

- [ ] New Command
- [X] Config option
- [X] Other

**Describe your feature**
I have the use-case for my network where we want global (Bungee) join and leave messages, and NONE on the Spigot side. So this would go for `welcome` messages as well. In the plugin's current state, it does not support welcome messages on the Bungee side. So I would like to request the ability for the plugin to store the joined players' UUID's in BungeeCord's RocketJoin directory (something to the effect of `plugins/RocketJoin/players.csv/dat/other/etc`).
This will allow the RocketJoin-Bungee WrappedPlayer https://github.com/Lorenzo0111/RocketJoin/blob/d245c74d16e3249ceb93f8508ce759f608034b97/bungeecord/src/main/java/me/lorenzo0111/rocketjoin/audience/WrappedPlayer.java#L35-L37 to check for existence in that datastore of previously joined UUIDs while in the area of https://github.com/Lorenzo0111/RocketJoin/blob/d245c74d16e3249ceb93f8508ce759f608034b97/bungeecord/src/main/java/me/lorenzo0111/rocketjoin/listener/JoinListener.java#L58-L61

To determine if the non-disabled welcome message should be broadcast.

Thanks and have a great day.

**Comment by Lorenzo0111** [comment]
Added
