### ISSUE TITLE
[BUG] player-placeholder takes wrong player for leave-message

### ISSUE THREAD

**Issue by Boy0000** [Lorenzo0111/RocketJoin#44]
**Explain your issue.**
When a player leaves, it tells the other clients they left. See video

**Are there any errors in the console? Use: link.rocketplugins.space/paste**
No errors

Config:
`join:
  enabled: true
  message: "&a+&f ┃ &b{player}"
  enable-title: false
  # Send a title to the player when he join the server!
  title: "&a&lWelcome {player}!"
  subtitle: "&7Welcome in ServerName Server!"

leave:
  enabled: true
  message: "&c-&f ┃ &b{player}"`

https://user-images.githubusercontent.com/62521371/143504905-2cfc18a6-f675-4cb9-b4b9-d0885c9bea07.mp4

**Comment by Boy0000** [comment]
Seems to have been fixed, but not in a released version

**Comment by Lorenzo0111** [comment]
Where are you running the plugin? (Velocity,spigot..)

**Comment by Lorenzo0111** [comment]
@Boy0000

**Comment by Boy0000** [comment]
Running it on Velocity, but the issue is only regarding latest release. Was fixed when i compiled it myself

**Comment by Lorenzo0111** [comment]
So the issue is that you have to disable join messages on your local servers. Read more [here](https://wiki.lorenzo0111.me/rocektplugins/rocketjoin/bungeecord#ive-rocketjoin-on-spigot-and-bungeecord-servers-it-is-double-posting-join-messages-how-can-i-fix).

**Comment by Boy0000** [comment]
The issue was tegarding the plugins leave registering wrong player. But its foxed. The vanilla msg i know about yeah

**Comment by Lorenzo0111** [comment]
ok
