### ISSUE TITLE
[BUG] Wrong work on Velocity

### ISSUE THREAD

**Issue by newjebv** [Lorenzo0111/RocketJoin#70]
**Type /rj bugreport and paste here the result.**
This team does not exist on Velocity

**Explain your issue.**
So. I put the plugin on velocity and it should show a message on login every time the player goes through the proxy (velocity), but for me it turns out that it shows a message every time they go to a new server (without going through the proxy). In fact, this is the same if I put the plugin on each server, instead of one velocity

**Are there any errors in the console? Use: link.rocketplugins.space/paste**

**Comment by Lorenzo0111** [comment]
You can set that string to empty to not send it
